"""fixing booking-experience relationship

Revision ID: 0cc0bae22dfe
Revises: fc28921d28ba
Create Date: 2026-02-16 18:54:35.632769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cc0bae22dfe'
down_revision: Union[str, Sequence[str], None] = 'fc28921d28ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
