"""unique key experiences

Revision ID: fc28921d28ba
Revises: f2eaa6593841
Create Date: 2026-02-16 17:32:30.091074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc28921d28ba'
down_revision: Union[str, Sequence[str], None] = 'f2eaa6593841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'experience', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'experience', type_='unique')
    # ### end Alembic commands ###
